language: java
addons:
  postgresql: "10"

before_install:
  - sudo apt-get update
  - sudo apt-get install -q postgresql-10 postgresql-client-10
  - sudo service postgresql start
  - psql -c "CREATE DATABASE gitclub;" -U postgres