language: java
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433

before_install:
  - psql -c 'create database gitclub;' -U postgres